In [7]:
import os
import pandas as pd
import json
os.chdir('/Users/jervermindah/Documents/University/TLCN/comprehensive-stockmarket-tool/technical_signal')
os.getcwd()
df = pd.read_csv('AAPL_signal.csv')

df.rename(columns={df.columns[0]: 'date'}, inplace=True)
df['date'] = pd.to_datetime(df['date'])

# Format the datetime values to "DD/MM/YYYY"
df['date'] = df['date'].dt.strftime('%d/%m/%Y')
df = df.fillna("")
df = df.to_dict(orient='records')

# Save the data to a JSON file
with open('AAPL.json', 'w') as file:
    file.write(json.dumps(df, indent=2))

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('AAPl_news_1.csv')
rows_to_remove = df[df['summary'].str.contains('Zacks.com', na=False, case=False)].index

# Remove the rows from the DataFrame
df.drop(rows_to_remove, inplace=True)
df.to_csv('AAPl_news_filter_non_zacks.csv')

In [2]:
import requests

url = "https://eodhistoricaldata.com/api/news"
params = {
    "api_token": "demo",
    "s": "AAPL.US",
    "offset": 0,
    "limit": 1000
}

response = requests.get(url, params=params)

if response.status_code == 200:
    data = response.json()
    # Process and work with the retrieved news data here
    print(data)
else:
    print("Error:", response.status_code)

Error: 401

In [5]:
import json
import os
def readjson(path):
    with open(path, 'r') as json_file:
        json_data = json.load(json_file)
    match json_data['symbol']:
        case 'APPLE':
            symbol = 'AAPL'
        case 'AMAZON':
            symbol = 'AMZN'
        case 'MICROSOFT':
            symbol = 'MSFT'
        case 'GOOGLE':
            symbol = 'GOOGL'
        case 'TESLA':
            symbol = 'TSLA'
    return symbol

print(os.getcwd())
symbol = readjson('../configs/symbolconfig.json')
print(symbol)

d:\New Technologies\Web_Stock\comprehensive-stockmarket-tool\notebooks
GOOGL

In [3]:
import json
objetc = {
    'asdas': 'asdasda',
    'asdasd': '123123'
}
with open('file_path.json', 'w') as file:
    file.write(json.dumps(objetc))

In [1]:
import datetime
import pandas as pd
os.chdir('../NLP/news_data/AAPL')
os.getcwd()
main_df = pd.read_csv('AAPL_data.csv')

In [5]:
main_df['date'] = pd.to_datetime(main_df['date'])
newest_date = main_df['date'].max()
current_day = datetime.date.today().strftime("%Y-%m-%d")
current_day = datetime.datetime.strptime(current_day, "%Y-%m-%d")
next_day = newest_date + datetime.timedelta(days=1)

In [3]:
import pandas as pd
import datetime as dt
import os

os.chdir('../csv/')
df = pd.read_csv('AAPL.csv')
df.rename(columns={df.columns[0]: 'date'}, inplace=True)
df['date'] = pd.to_datetime(df['date'])

# Filter the dataframe to get dates before February 5, 2023
df = df[df['date'] < '2023-05-02']
df.tail(10)

,date,close,open,high,low,adjusted close,volume,WILLR_14,SMI_7_14_5,SMIs_7_14_5,...,BBL_14_2.0,BBM_14_2.0,BBU_14_2.0,BBB_14_2.0,BBP_14_2.0,SMA_14,EMA_14,VWAP_D,HMA_14,CMF_20
5902,2023-04-18,166.47,166.100,167.4100,165.6500,166.238805,49923008.0,-11.662531,0.245072,0.230391,...,159.615189,163.832143,168.049096,5.147895,0.812768,163.832143,163.116034,166.510000,164.391071,0.266199
5903,2023-04-19,167.63,165.800,168.1600,165.5400,167.397194,47720166.0,-6.324582,0.282166,0.247649,...,160.048468,164.322143,168.595818,5.201581,0.887004,164.322143,163.717896,167.110000,165.626071,0.236041
5904,2023-04-20,166.65,166.090,167.8700,165.5600,166.418555,52456377.0,-18.019093,0.280983,0.258760,...,160.346403,164.628571,168.910739,5.202217,0.736029,164.628571,164.108844,166.693333,166.710063,0.309948
5905,2023-04-21,165.02,165.050,166.4521,164.4900,164.790819,58337341.0,-37.470167,0.234779,0.250767,...,160.352356,164.637143,168.921929,5.205127,0.544676,164.637143,164.230331,165.320700,167.138730,0.309945
5906,2023-04-24,165.33,165.000,165.6000,163.8900,165.100388,41949581.0,-33.770883,0.208249,0.236594,...,160.356856,164.577143,168.797430,5.128643,0.589195,164.577143,164.376954,164.940000,167.008532,0.289499
5907,2023-04-25,163.77,165.190,166.3050,163.7300,163.542555,48714063.0,-52.386635,0.146077,0.206422,...,160.247901,164.444286,168.640670,5.103716,0.419659,164.444286,164.296026,164.601667,166.355230,0.281097
5908,2023-04-26,163.76,163.055,165.2800,162.8000,163.532569,44105745.0,-52.505967,0.102190,0.171678,...,160.247901,164.444286,168.640670,5.103716,0.418467,164.444286,164.224556,163.946667,165.515373,0.256870
5909,2023-04-27,168.41,165.190,168.5600,165.1900,168.176111,64902329.0,-1.708428,0.170972,0.171442,...,160.042801,164.712143,169.381485,5.669700,0.895972,164.712143,164.782615,167.386667,165.513746,0.277468
5910,2023-04-28,169.68,168.490,169.8500,167.8801,169.444347,55275851.0,-1.688183,0.236637,0.193174,...,160.198499,165.258571,170.318644,6.123825,0.936894,165.258571,165.435600,169.136700,166.310437,0.281052
5911,2023-05-01,169.59,169.280,170.4500,168.6400,169.354472,52472936.0,-8.059981,0.276352,0.220900,...,161.017321,165.886429,170.755536,5.870411,0.880313,165.886429,165.989520,169.560000,167.476444,0.225059

In [12]:
import pandas_ta as pt
help(pt.cmf)

Help on function cmf in module pandas_ta.volume.cmf:

cmf(high, low, close, volume, open_=None, length=None, offset=None, **kwargs)
    Chaikin Money Flow (CMF)

    Chailin Money Flow measures the amount of money flow volume over a specific
    period in conjunction with Accumulation/Distribution.

    Sources:
        https://www.tradingview.com/wiki/Chaikin_Money_Flow_(CMF)
        https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:chaikin_money_flow_cmf

    Calculation:
        Default Inputs:
            length=20
        if 'open':
            ad = close - open
        else:
            ad = 2 * close - high - low

        hl_range = high - low
        ad = ad * volume / hl_range
        CMF = SUM(ad, length) / SUM(volume, length)

    Args:
        high (pd.Series): Series of 'high's
        low (pd.Series): Series of 'low's
        close (pd.Series): Series of 'close's
        volume (pd.Series): Series of 'volume's
        open_ (pd.Series): Series of 'open's. Default: None
        length (int): The short period. Default: 20
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.